spring:
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ieum}
    username: ${DB_USERNAME:ieum}
    password: ${DB_PASSWORD:ieum}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
